### ISSUE TITLE
登录页面进不去

### ISSUE THREAD

**Issue by hehahah** [ChengHo/CinemaBookingSystem#11]
大佬 这个登录页面的管理员账户是admin，密码是啥啊？数据库里面的密码加密过了 我前端页面一登上去 后端就报错 显示token值为0 进不去购票界面，求解答

**Comment by codee-vip** [comment]
运行了吗？我这边运行起来了，能跑，用户能登陆
![image](https://user-images.githubusercontent.com/20723516/220371053-eb2c8304-a1ab-4c3f-b42f-cced56633acf.png)

**Comment by ChengHo** [comment]
应该是123456吧。你可以尝试把后台登录校验关闭，自己调注册接口。把新注册的密码和salt替换上去
