### ISSUE TITLE
前端进不去哇

### ISSUE THREAD

**Issue by hehahah** [ChengHo/CinemaBookingSystem#12]
大佬 前端页面密码总是错 进不去系统 [[这是为什么啊？
![image](https://user-images.githubusercontent.com/106375354/220618933-ccf380ea-b38c-4bfe-be74-603be88b2980.png)
![image](https://user-images.githubusercontent.com/106375354/220619246-2bf050c0-d2f4-4b24-9bd2-d0fd6ceb57e9.png)

**Comment by ChengHo** [comment]
你留个VX吧。我加你

**Comment by hehahah** [comment]
yy09020000


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChengHo/CinemaBookingSystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChengHo/CinemaBookingSystem] 前端进不去哇 (Issue #12)





 
你留个VX吧。我加你
