### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by StrugglingA** [ChengHo/CinemaBookingSystem#7]
![image](https://user-images.githubusercontent.com/50633270/161368153-712d18cf-9930-49ba-a735-f0cc8c0f5191.png)
老哥你用的quartz是干嘛的

**Comment by boohue** [comment]
有一个用户提交的订单未支付15分钟自动取消的逻辑（实际没有实现，用的是定时轮询[5分钟检查一次数据表，超时取消订单，释放座位资源占用]）

**Comment by StrugglingA** [comment]
并没有实现这个功能嘛？

**Comment by boohue** [comment]
实现了啊，但是不是按照实际需求实现的。实际需求时订单提交15分钟未支付取消，但是这个我没实现，换了一个逻辑实现（每5分钟遍历订单数据表，发现有超过15分钟没支付就取消它）（还有一个控制超时取消的实现，就是管理端访问订单时会调用一次超时取消的方法，用户端访问座位信息时也调用了一次超时取消订单的方法）

**Comment by boohue** [comment]
如果你有更好的实现方法，你可以编写代码提交过来，我会给你合并上去的。如果你真这样做了，那真是感激不尽

**Comment by boohue** [comment]
代码里面你查看历史应该能看到有记录操作log的实现，不过这个当时我没完善，就后来中途删了。有需要你也可以完善它

**Comment by ChengHo** [comment]
还有问题吗？没疑问我关issue了？

**Comment by StrugglingA** [comment]
问题是我现在甚至运行不起来，根本无法看到长什么样子，更没法完善了理解逻辑了

**Comment by ChengHo** [comment]
？你这个只是后端运行了。这是个前后端分离的项目，你前端有运行吗？

**Comment by boohue** [comment]
有需要+wx吧，有啥问题尽量帮你解决boohue

**Comment by StrugglingA** [comment]
WX多少啊

**Comment by boohue** [comment]
boohue

**Comment by StrugglingA** [comment]
搜不到的 你加我吧Struggling_37N120E非常感谢
