### ISSUE TITLE
购票页面有问题

### ISSUE THREAD

**Issue by TankLin23** [ChengHo/CinemaBookingSystem#8]
兄弟为什么购票返回的订单是null啊
![image](https://user-images.githubusercontent.com/58041109/166502844-9042662e-6d34-4d92-ac0f-50f0adec5a8f.png)

**Comment by ChengHo** [comment]
已修复

**Comment by nmy1223743788** [comment]
作者大大 我购票界面显示不出来 
![image](https://user-images.githubusercontent.com/78782118/167654828-088e952d-9393-4d28-a17f-2e19dd100cfc.png)
然后点击特惠选票又跳回到上个界面
![image](https://user-images.githubusercontent.com/78782118/167654976-540901f1-1cbe-49a6-9fe1-ac9f5c8c2ee8.png)
求大大解决 快毕业答辩了 大哭

**Comment by ChengHo** [comment]
要后台管理那里设置电影信息，电影场次信息。需要当前时间有电影场次数据才会有数据展示。毕设都是2021年写的了，现在肯定是没有对应要开场播放的电影场次了。这些数据肯定是需要有人不断维护才会有的。

**Comment by hehahah** [comment]
大佬 这个登录页面的管理员账户是admin，密码是啥啊？数据库里面的密码加密过了  我前端页面一登上去 后端就报错 显示token值为0 进不去购票界面，求解答
